### ISSUE TITLE
evobuild in RAM

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/package-management#1]
Is it viable to make a RAMdisk for the union/work directories so that all of that disk IO is avoided. It would reduce disk degradation and improve performance.

**Comment by ikeydoherty** [comment]
It is technically possible - but I wouldn't recommend it without having significant RAM available.. For example you won't be building LibreOffice in RAM.

**Comment by Justinzobel** [comment]
Yeah of course. But for the tons of normal sized apps it would be good.
Millions of iops on an SSD is no good for it.

**Comment by ikeydoherty** [comment]
evolbuild is dead but solbuild supports `-t` option now, implementing this
