### ISSUE TITLE
Suggestion about release naming

### ISSUE THREAD

**Issue by examachine** [solus-project/package-management#12]
Hello there,

I'm the original author of PISI from Tubitak 2005/2006. I am maintaining the abandoned original development branch of pisi here: 
https://github.com/examachine/pisi

The releases you are making is a fork of Pardus stable branch, however, it is not informative to make major releases of PISI as you like, you probably should instead call your branch "solus-1.x" "solus-3.x" or otherwise. Just a suggestion, but the planned pisi releases are 3.x and 4.x, and you've already named your releases 3.x. I know you have your own ideas about how you would like PISI to be, but you cannot simply adopt a package manager that is already developed by others and not abandoned, Pisi Linux is also maintaining releases off the stable branch, but this naming will be a problem. 

Anyhow, I will name the development branch releases "devel-3.x" and so forth, and to avoid confusion with the "stable" branch, the new stable releases will be named something else, but here see this, you've already called your code "solus-project/package-management", you can use the pisi name in your tools if you like it so much, but if you release it like this it might be disrespectful to the original Pardus naming scheme where we had a stable and a devel branch. You are making major changes I get it, but as the original author, I might not agree with them, and they are not part of the roadmap I've had for the development branch. Please take this as a friendly suggestion to avoid naming clutter in the future.  I would also be grateful if you acknowledged the original authors (there were 4 authors) properly -- future maintainers made a mess of all the code, including the AUTHORS and TODO files, which is why I discarded most arbitrary changes in the stable branch that crippled PISI libs. Anyhow, I think you'll find the original devel releases intriguing. And if you'd like to talk about what changes you are planning, just shoot me a message at gmail.

Kind Regards,

Dr. Eray Ozkural

**Comment by ikeydoherty** [comment]
Hi, I'm glad you reached out. If there are any missing original files, please open a PR and we'll add them to the repo.

Please note that pisi is no longer referred to as pisi in Solus itself, the files installed are `eopkg`. The repo  was also renamed as `package-management`.  The package manager itself is labelled `/usr/bin/eopkg`. 

Now, you claim the package manager was not abandoned, this is not true. The package manager was left for dead when I first adopted it several years ago. I originally intended to continue the development, but the Pardus Anka group objected most abusively to that (now known as Pisi Linux). They do not publicly develop their fork of pisi in a way that can be collaborated with, by applying patches to a privately developed tarball. The version we use is of *eopkg*, not *pisi*. There is no namespace conflict.

Thus the fork was done as a complete separation from those groups. I think it's a bit disingenuous to claim it's not abandoned, or indeed that this is a friendly request. The package manager saw no public development for years. All SVN resources disappeared. I don't think there is any disrespect to the Pardus naming from the Solus side, given that version of Pardus is dead, all original works disappeared, and we made absolutely sure to distance this version of the package manager from the original, ensuring from the outset that packages would not be binary compatible with the original (`eopkg-index` vs `pisi-index`, `.eopkg` vs `.pisi`) - not to mention we use automatic binary runtime dependencies, and PkgConfig provides to achieve much simpler build management.

>  I am maintaining the abandoned original development branch of pisi here:

 I watched you recently restore your repository, this is long after the works had been done in this repo. I've watched the creation and subsequent alterations you've made. I'm more than aware of the timeline.

As for furthering pisi, the plan is to deprecate it from Solus. In short, python is too slow, and pisi employs legacy constructs we deem unsuitable in Solus going forward (such as comar, python-dbus within the root, etc.)

Also note we do not use pisi's build format anymore, we use ypkg to build the resulting packages. Our goal is to construct a solid successor, suitable to Solus itself.

**Comment by ikeydoherty** [comment]
While I'm here though I do want to thank you for your original work on pisi. It has served Solus well, and the "one tool approach" will serve as inspiration for our next iteration.

**Comment by examachine** [comment]
Hi there, thanks for the clarification. I only said this, because I saw the pisi-3.x release not realizing when it is made, I thought you were _continuing_ to make PISI releases parallel to solus/package-manager, my bad. 

And yes you might be right about various development conflicts. I know they are maintaining patches over a tarball, that is not enough either. And even I couldn't find the development branch here: 
http://svn.pardusproject.org/

Though this would be the "last" official repository that I have seen, doruk fisek maintains it, not the pardus anka team. I note that pisi linux team has their own ideas, but they are actually quite fond of the direction you have with solus package manager (They ask me to use JSON instead of XML etc.). I just want to make sure there are no naming conflicts in the future. And yes, the suggestion is friendly, because I thought you still wanted to use the pisi libs in the backend, but you want to completely drop python, I didn't notice that. What are you going to use instead?

I will try to make PISI a library that does address your concerns (about comar, etc.) and concerns of other distros, so I thought solus at once point used it, and pisi linux uses it, and there is another distro under development that uses it, really just trying to provide a better base for all distros that might *wish* to use PISI in the future. So, I'm thinking like I'll remember all the features I had planned for it and resurrect some code that was stripped etc. and make another major release with all the goodies in it.

So, anyhow, I'll make sure the new devel and stable branches are named "devel" and "kitty" to avoid any version conflicts. But glad to know we won't be having parallel releases with the same name that would surely confuse the hell out of package developers. :) That would be like having multiple versions of dpkg, not really a great thing.

Happy Hacking,

Eray

**Comment by ikeydoherty** [comment]
Yeah definitely a "bad thing" to have multiple pisis. For us we'll develop a self contained replacement as a static binary. One of the problems with a Pythonic package manager is that it is at the mercy of its own upgrades. As a concrete example, lazy initialisation of comar lead to a broken upgrade path a while back when we switched Python from UCS2 to UCS4. Comar was loaded *after* it was updated, so the host process was UCS2 and the new libraries used UCS4. It's too delicate an approach imo (the same situation will arise from a switch from Python 2 to Python 3)

I'll make sure to point people to your official repos if you want, just give me the links.

As for ypkg, it actually uses YAML, not JSON. It's pretty damn easy to use and automates the majority of the jobs. You should probably also look at `solbuild`, an overlayfs based container build system for binary packages. The rule being that every package is built within its own chroot, unlike buildfarm which will cumulatively build within the same root for a given queue. 

And fwiw, for the remainder of the lifetime of eopkg, I'll happily backport your fixes/cleanups, because in truth the codebase in this tree is a bit of a mess right now (No pep8/flake8 CI)

**Comment by examachine** [comment]
Overlayfs seems like a good idea. We actually thought of doing something like that back in the day but then dropped it. I do have an open issue for supporting containers in pisi-devel branch. Pisi linux also uses docker I think in their build thing. So it seems like everyone wants containers nowadays, and that's probably a good thing.

Yeah, I think they saw YAML and wanted YAML or JSON but that's too much of a change IMO. Still quite interesting, of course. It does look nice.

I agree with the dependency problems, COMAR is nice for a variety of reasons, but it probably needed some more love. What COMAR does in pisi, aside from installing config files still isn't clear to me, though. :P  I mean, it probably can be done without COMAR, I am trying to make that dependency optional but I also think a tool like debconf or COMAR has many uses, it just has to be better tested, developed and of course *documented*. 

As for the mess, well, yes, it did look messy so I thought I would make the original berkeley-db version work right with the extra devel features also working and the code cleaned up a bit, you might find it interesting, and I'll announce other PISI library related developments.

Thanks for the suggestions! <3

**Comment by examachine** [comment]
PS: I am actually developing right now on OS X to make sure PISI is portable.
