### ISSUE TITLE
installation of local packages

### ISSUE THREAD

**Issue by Tcll** [solus-project/package-management#17]
it doesn't seem to be possible to install `.eopkg` files in the same way `.deb` files can be installed on Ubuntu-based distros.

I've been using Xubuntu for years without internet (can't afford it), so I've built up quite the database of .deb files...
so after finding out I couldn't install from that collection, I decided to look into downloading the eopkg files I needed.

but I wanted to note, not being able to install by double-clicking the file is keeping me from progressing on this latest installation of Solus 3. :/

**Comment by Tcll** [comment]
if you're questioning how I have such a database in the first place, this phone is quite a handy tool.
it may not be able to host a valid hotspot, let alone teather including through adb, but it can transfer quite a bit of downloaded content.

**Comment by Justinzobel** [comment]
You can install .eopkg files from your terminal, `sudo eopkg install some.eopkg` you'll also need to know what dependencies it has (could be multiple levels).

**Comment by Tcll** [comment]
how would I figure that out btw??
solus-sc doesn't exactly tell me the exact urls like I'm used to with Xubuntu...

I want to note though, for now, I'm working on formatting with Xubuntu 16.04
Solus is very nice, and lives up to the performance I was told about (the reason I installed),
but it's not exactly mature enough for someone like me to start using it yet with all the stuff I do.

**Comment by Justinzobel** [comment]
It's not designed to be used offline, like most modern Operating Systems, you'd have to manually follow the dependency tree down and get all the required versions.

**Comment by Tcll** [comment]
woah there, quite a majority of those modern OSs can be used just as well offline as they can online.
Xubuntu is one of them.
and if you really want to get into it, Windows 8 is just as usable (almost) as XP offline.

a proper OS should not rely on internet as it's only source of use.

**Comment by Justinzobel** [comment]
Solus can be used fine offline, but it requires documenting each dependency you'll need and grabbing them.

**Comment by Tcll** [comment]
just one last note for any final validation...
you're sure you may not be thinking of any applications I can use with grep to list the dependencies I need??

this is exactly the method I have to fall back to on Xubuntu if the software center proves uncooperative.

**Comment by Justinzobel** [comment]
`eopkg info packagename` will tell you what it depends on, however those packages may have dependencies of their own. So you have to trace it all the way back to make sure you get each eopkg.

**Comment by ikeydoherty** [comment]
This repository is for the **command line** eopkg tool, so it wouldn't handle "double clicking" ever.

As indicated, you install a local package with:

`sudo eopkg it $path-to-eopkg-file`

The Software Center (solus-sc) project will gain local file support in time.

**Comment by Tcll** [comment]
can't wait :)
