### ISSUE TITLE
man page missing some commands

### ISSUE THREAD

**Issue by nursoda** [solus-project/package-management#25]
While reading https://getsol.us/2018/09/11/package-repo-migration-now-available/ I noticed two commands I didn't know what the abbreveation meant:
```
sudo eopkg dr Solus
sudo eopkg rr Solus
```
So I tried to look them up via man eopkg but noticed, that neither disable-repo nor remove-repo are described in the man page. I only know the long commands from trying to execute the above commands.

Please check the manpage for implemented but yet undocumented commands.

**Comment by AvdN** [comment]
They might not be in the manual, but they are in the output of `eopkg -h`, so reverting to execution of unknown commands to check what they do seems unnecessarily dangerous.

eopkg, like so many python based programs, generates the help on the fly from the actual commandline parser, so it is always up-to-date.

**Comment by DataDrake** [comment]
```
disable-repo (dr) <name>

           Disable a system repository. It will no longer be accounted for
           in any operation, including search, install, and updates.
```
`remove-repo` is the only one missing.

Not going to take the time to fix this anyway because eopkg is in maintenance mode until we replace it. Any changes we make from here on out will be to ease the transition.
