### ISSUE TITLE
Is this project no longer mantained?

### ISSUE THREAD

**Issue by Davidmp1** [solus-project/package-management#30]
Since latest pull request is from more than a year ago...

**Comment by JoshStrobl** [comment]
You're looking at the wrong organization. Check https://github.com/getsolus/package-management but regardless, eopkg is not actively developed seeing as our intent is to replace it with sol.

**Comment by Davidmp1** [comment]
Hello,

All that I ask is for the eopkg package manager in Solus to get all pending
(more than a year ago) corrections and modifications regarding translations.

Thanks,

David

Missatge de Joshua Strobl <notifications@github.com> del dia dj., 14 de
març 2019 a les 11:35:

**Comment by JoshStrobl** [comment]
We have no plans on making any changes to eopkg.

**Comment by Davidmp1** [comment]
Hello,

This is very very discouraging and very very disappointing!

At least you could pull in all pending changes in order to profit from the
latest contributions and corrections so that the people who did them didn't
loose their time! It would be a good consideration. Once this done, close
the possibilty to add more modifications and requests.

And if the plan is to develop sol and to make all that there is to
translate available in Weblate, the best would be to transfer the latest
version of the tranlations from Tansifex and Git (eopkg) with latest
changes applied so as to not to have to redo on Weblate what had already
been done (as it happened recently). There are still translations from
Transifex for solus-sc that have not been appied to the system.

Thanks,

David


Missatge de Joshua Strobl <notifications@github.com> del dia dv., 15 de
març 2019 a les 14:58:
