### ISSUE TITLE
Old pisi name still present in some messages

### ISSUE THREAD

**Issue by ffigiel** [solus-project/package-management#4]
eopkg suggests to run pisi in some messages:

<pre><code>
filip@solus ~ $ sudo <strong>eopkg</strong> install npm
System error. Program terminated.
Repo item npm not found
Please use '<strong>pisi</strong> help' for general help.
Use --debug to see a traceback.
</code></pre>

By the way, is it known when npm package will be added to solus repo?

**Comment by JoshStrobl** [comment]
This was fixed as of 264093c453380db6e07273f8b616b643ea384916 and we just need to update it in the Solus repo.

Also, nodejs provides npm. Not that this is the place to talk about repo inclusion.
