### ISSUE TITLE
Solus lacks basic encryption capability encfs, luks-crypt, etc.

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/package-management#7]
Solus has no basic encryption support other than may be with zip files with passwords.

http://www.cyberciti.biz/hardware/howto-linux-hard-disk-encryption-with-luks-cryptsetup-command/

In my Office I want to keep my documents encrypted, but solus has no encfs nor partition encryption. 

Also there's no nfs support.

Please consider encryption support so that Solus could be used in workplace. Thank you.

**Comment by ikeydoherty** [comment]
Please don't open issues here, this is for eopkg itself. Encryption support is planned for 1.2.1, known issue.
